### ISSUE TITLE
Crash when tapping on welcome screen

### ISSUE THREAD

**Issue by glwisnia** [wlky/AnkiDroid-Wear#1]
When tapped on the welcome screen with "Hello" message app will instantly crash.
![ankiwear](https://cloud.githubusercontent.com/assets/12797174/8034689/f786d580-0de1-11e5-8d73-94baeb9cbbc2.jpg)

**Comment by wlky** [comment]
that was quick :D
But good to know that installing the apk etc. worked :)

fixed the issue btw. but I'm gonna wait a bit before making a new build. Hope you can live with that bug for now :P
