### ISSUE TITLE
Support Voice Gestures

### ISSUE THREAD

**Issue by elgalu** [wlky/AnkiDroid-Wear#11]
By using [Pre-defined Text Responses](https://developer.android.com/training/wearables/notifications/voice-input.html)

For example:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string-array name="reply_choices">
        <item>Again</item>
        <item>Good</item>
        <item>Easy</item>
    </string-array>
</resources>
```

**Comment by wlky** [comment]
The link you provided seems to be restriced to notifications. Since I'm not really dealing with notifications I'll close this issue
