### ISSUE TITLE
Wrong report on the study time

### ISSUE THREAD

**Issue by glwisnia** [wlky/AnkiDroid-Wear#2]
The time spent in AnkiDroid Wear reviewing cards does not get counted towards the statistics in AnkiDroid. If I do all my cards on the watch (let's say 100 of them), after I'm finished I'll go to AnkiDroid and it will say that I've done 100 cards in 0 seconds.

**Comment by wlky** [comment]
I'm on it, but it requires another change in the AnkiDroid implementation, so it might take a little till its in the next release

**Comment by wlky** [comment]
the change was merged and the fix should come with the next version of AnkiDroid and AnkiDroid Wear
