### ISSUE TITLE
"Show deck counts" feature missing in GitHub code.

### ISSUE THREAD

**Issue by LemmusLemmus** [wlky/AnkiDroid-Wear#28]
When building the project for pull request #27 I noticed that the "show deck counts" feature added in the [latest release](https://github.com/wlky/AnkiDroid-Wear/releases/tag/1.0alpha31) was missing. The code changes from 2017 appears to have not yet been submitted to this repository.

Sorry if I'm being an annoyance with my recent activity on this repository.

**Comment by wlky** [comment]
Your not at all an annoyance, I'm glad someone is taking the time to look at it all.
I actually myself have forgotten a whole lot of what I did in this Project, but could it be that what you are looking for is on the develop branch?

**Comment by LemmusLemmus** [comment]
@wlky Ooooooh, that explains things! I didn't realize that there existed such a thing. Thanks!
Should my pull request be removed and resubmitted to the dev branch then?
