### ISSUE TITLE
Enable open alpha testing and update usage instructions

### ISSUE THREAD

**Issue by timrae** [wlky/AnkiDroid-Wear#7]
AnkiDroid 2.5 has officially been released, and Google Play now allows "Open alpha testing" whereby anyone can become an alpha tester without having to join a Google Group. Please update your usage instructions, and also I recommend using the open alpha/beta mode.

By the way, did you end up resolving the issues with Google Play? It seems that your app is still not accessible on Play.

**Comment by timrae** [comment]
Or maybe just skip beta and release it...

**Comment by wlky** [comment]
Thanks for the info.
No I haven't gotten a single email from google play in response to my request to re enable my app...
Between the waiting for a resolution of the problem and other projects of mine, I sort of abandoned AnkiDroid wear.
But I'll try to do some work on it now that Anki 2.5 is released and try to release it as well under a different name+different picture

**Comment by wlky** [comment]
Open alpha is enabled and the v1 is released :)
time to buy a smartwatch ;P

**Comment by timrae** [comment]
Great, I think you meant to link to the AnkiDroid play listing in the Installation section though?

**Comment by wlky** [comment]
yeah, I guess that makes more sense
